# permissions for end users to view packagedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packagedeployment-viewer-role
rules:
- apiGroups:
  - automation.nephio.org
  resources:
  - packagedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - automation.nephio.org
  resources:
  - packagedeployments/status
  verbs:
  - get
