# permissions for end users to edit packagedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packagedeployment-editor-role
rules:
- apiGroups:
  - automation.nephio.org
  resources:
  - packagedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.nephio.org
  resources:
  - packagedeployments/status
  verbs:
  - get
