# permissions for end users to view clusterscaleprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterscaleprofile-viewer-role
rules:
- apiGroups:
  - infra.nephio.org
  resources:
  - clusterscaleprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.nephio.org
  resources:
  - clusterscaleprofiles/status
  verbs:
  - get
