# permissions for end users to edit clustercontexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustercontext-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nephio
    app.kubernetes.io/part-of: nephio
    app.kubernetes.io/managed-by: kustomize
  name: clustercontext-editor-role
rules:
- apiGroups:
  - infra.nephio.org
  resources:
  - clustercontexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.nephio.org
  resources:
  - clustercontexts/status
  verbs:
  - get
