
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: infra-controller
  namespace: nephio-system
  labels:
    app: infra-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-controller
  template:
    metadata:
      labels:
        app: infra-controller
    spec:
      containers:
      - name: infra-controller
        image: ntnguyencse/infra-controller:v0.5
        imagePullPolicy: IfNotPresent 
        # command: ['sh', '-c', 'sleep 500']
        env:
          - name: PROVIDER_API_SERVICE_URL
            value: PROVIDER_API_SVC_HOST
        ports:
          - containerPort: 3334
            name: infra-svc
---
kind: Service 
apiVersion: v1 
metadata:
  name: infra-controller-service
  namespace: nephio-system
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster 
  type: NodePort

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: infra-controller

  ports:
    - name: infra-controller-port
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
      port: 3334 
      targetPort: infra-svc