.PHONY: all
all:
	@echo "**********************************************************"
	@echo "**                    Provider API Service Builder*     **"
	@echo "**********************************************************"


.PHONY: run
run:
	go run .