apiVersion: infra.nephio.org/v1alpha1
kind: ClusterScaleProfile
metadata:
  name: small-fixed-site
spec:
  autoscaling: false
  nodeMax: 6
  siteDensity: low
---
apiVersion: infra.nephio.org/v1alpha1
kind: ClusterScaleProfile
metadata:
  name: medium-fixed-site
spec:
  autoscaling: false
  nodeMax: 12
  siteDensity: medium
---
apiVersion: infra.nephio.org/v1alpha1
kind: ClusterScaleProfile
metadata:
  name: medium-autoscaling-site
spec:
  autoscaling: true
  nodeMax: 24
  siteDensity: medium
---
apiVersion: infra.nephio.org/v1alpha1
kind: ClusterScaleProfile
metadata:
  name: large-fixed-site
spec:
  autoscaling: false
  nodeMax: 600
  siteDensity: high
---
apiVersion: infra.nephio.org/v1alpha1
kind: ClusterScaleProfile
metadata:
  name: large-autoscaling-site
spec:
  autoscaling: true
  nodeMax: 2400
  siteDensity: high
