
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: provider-api-service-controller
  namespace: nephio-system
  labels:
    app: provider-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-api-service
  template:
    metadata:
      labels:
        app: provider-api-service
    spec:
      nodeSelector:
          kubernetes.io/hostname: hyfast-mgmt01
      containers:
      - name: provider-api-service-deployment
        image: ntnguyencse/provider-api-service:v1.16
        imagePullPolicy: Always
        env:
          - name: KUBECONFIG
            value: /kubeconfig/config
          - name: OPENSTACK_FAILURE_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-failure-domain 
          - name: OPENSTACK_IMAGE_NAME
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-image-name 
          - name: OPENSTACK_EXTERNAL_NETWORK_ID
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-external-network-id 
          - name: OPENSTACK_NODE_MACHINE_FLAVOR
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-node-machine-flavor 
          - name: OPENSTACK_DNS_NAMESERVERS
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-dns-nameservers 
          - name: OPENSTACK_CONTROL_PLANE_MACHINE_FLAVOR
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-control-plane-machine-flavor
          - name: OPENSTACK_SSH_KEY_NAME
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-ssh-key-name 
          - name: OPENSTACK_CLOUD
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-cloud
          - name: OPENSTACK_CLOUD_CACERT_B64
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-cloud-cacert-b64
          - name: OPENSTACK_CLOUD_PROVIDER_CONF_B64
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-cloud-provider-conf-b64
          - name: OPENSTACK_CLOUD_YAML_B64
            valueFrom:
              configMapKeyRef:
                name: openstack-env
                key: openstack-cloud-yaml-b64
        ports:
          - containerPort: 3333
            name: pvd-svc-port
        volumeMounts:
        - name: kubeconfig
          mountPath: /kubeconfig
      volumes:
      - name: kubeconfig
        configMap: 
          name: clusterapi-management-kubeconfig
      # env:
      #   # Define the environment variable
      #   - name: SPECIAL_LEVEL_KEY
      #     valueFrom:
      #       configMapKeyRef:
      #         # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
      #         name: cluster-api-kubeconfig
      #         # Specify the key associated with the value
      #         key: special.how
---
kind: Service 
apiVersion: v1 
metadata:
  name: provider-api-svc
  namespace: nephio-system
  # PROVIDER_API_SVC_SERVICE_HOST
  # PROVIDER_API_SVC_SERVICE_HOST
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster 
  type: NodePort

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: provider-api-service

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - name: pvdapi-svc
      port: 3333 
      targetPort: pvd-svc-port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openstack-env
  namespace: nephio-system
data:
  # property-like keys; each key maps to a simple value
  openstack-failure-domain : "compute"
  openstack-image-name: "ubuntu-k8s-1.24"
  openstack-external-network-id: "faa68d67-0441-4749-895b-95ac49f85d86"
  openstack-control-plane-machine-flavor: "cluster.controller"
  openstack-dns-nameservers: "8.8.8.8"
  openstack-node-machine-flavor: "cluster.compute"
  openstack-ssh-key-name: "clusterapi"
  openstack-cloud: "starlab-cloud"
  openstack-cloud-cacert-b64: "Cg=="
  openstack-cloud-provider-conf-b64: "W0dsb2JhbF0KYXV0aC11cmw9bnVsbAo="
  openstack-cloud-yaml-b64: "Y2xvdWRzOgogIHN0YXJsYWItY2xvdWQ6IG51bGwK"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterapi-management-kubeconfig
  namespace: nephio-system
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1URXlPVEE0TURBME1Gb1hEVE15TVRFeU5qQTRNREEwTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmVnCkxFOC8veW5uU3cvTW1sM2l5Qm9EajZia0s4cE94d3JDL2RWTWl6enZMWmMvcGdnSDgrc0xLL3hiTCswYXNmcjMKM3U4V2JsdE1MVWJrdU5qeDJMUDNZNUQyZncyYUxmQytubkZnYzhsdG40T1lOcjVXR0U1UHZaSXRqNzFnWlo4SQp5bmxFUURIRG1iMXp3NG9odllpZ0hXNnpwV2MxbXFVSzROcC9jcmM3QlYzUmt6Y3dWeTBER2hhaGN1d0dsbG9LCldJclNRc3RwK0F4VmxDTkU2TkF2RmVQNE9Hekx1UDNPWTd2OTVCYXJGa0E3dWRBbFFqYzJTY3daWEsyL3JnalcKbmZ6eWNhZ2l1Umo5bEw5enV1Z1lBMzAvMEVjS0w2b3M5ODUzelZiaEw2WXFWY0lDK2Rxa3paYkNUYngwOU9HNQpTbFJMMHdkT2w1aTZCNGVpYkRrQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDalBSVndsazRQZE9WV0xkU3diY0tEQ1ExcE9NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRlA2TUVMYUpFMExRRUs2eTFXegoranQ0VDVYWjM5NDUzSk8vQkRSSzg2WDMxUFNSMUZXQ0VZS3ZFb0RkZWwwTGROVndjTTFNb1RKTWFoRVZVK2cxCkRVL09LaUFFTTVwUjZNOHo3Rm9aQUo0ZVJQYTJ2MTFZRnNBcmYrVnFUL3ljY2JiN2l5Y1JROXA5czBFZUdpNzEKa3Y2RXdmendMUUZpN0ZVMkl5Y1FQTys4VXdNSlQyNlMyTWN6aGNBZkdxbmcya3IwblpLQlBReXZWaUJIdEpLSQpjRUJHWm5Kc2hJQWJRdjU3L3MwNFRVMmwzM0RSWS9OMXNBM1ZrZDlTc3VaMlRzbmVoL0UwSlBRTzE4RWtKMXk1CmtSRzZzNXNWckI2STdMc2RQTFpPV2lvaWFTSTFUZWhZblNyRzRmM3R1bFBIaXM1LzNyd2lCSUdweGd4SkREQUoKYTJrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://hyfast.starlab.dcn:6443
      name: hyfast
    contexts:
    - context:
        cluster: hyfast
        user: kubernetes-admin
      name: kubernetes-admin@hyfast
    current-context: kubernetes-admin@hyfast
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJSDRPV1c5Wml6OXN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpFeE1qa3dPREF3TkRCYUZ3MHlNekV4TXpBd05UUTJNRGxhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXU4RVptNkUzc1Z0emVkVGoKU24xL2hEczRTM0JoN1NFTGFINEVHdU1ySVpISVorbWdNUzJlcjdHQzZ1RDJaY3BiMnBTVGhCVmUwWjhja3BwbQpHMG5ncStmWnNpNjloVHRDcGk1OVhTWmhBdUNKYzhGbDNVSk1ramhEbXRqZWlFV1FYZmxFZUU4M2JjT2IwZHdPCmRHOUtzRStnUFlleUhiZ2NuL3Y5UXk2M1N0SjZEZWFuT0l3dTdYQWdSRDY2dVdpWU9rbFB5a2dCVzFzYUcvRlYKZUhJb1laTy9NTW5MaEw5TUU5and2a0dVVzZJNXI2WDN0SFFkTjVZcG1vNEU2S2pEdy9mTTl3OWV1TTR2VTVWRgpXcG9IUzRFSFZxa2FqY21ZbEVPWU9sM3BYSjlFTmpNTUtsalJRQUxJdTRDSWc0Zzd5NlFRcDNacmkrb2JFNlpnCjh6TGhtUUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JRb3owVmNKWk9EM1RsVmkzVXNHM0Nnd2tOYQpUakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBakxKUDdUQ2VJcG03OW8va0sreERUdDUwRXA1WVk1ZmZUS3VzCkswWTFVTHcyemRIQ3hoSUdVeDlJNTNXS0xEUmVodEVPVzRDYzNZN2VLWjdZY0tDbTJ4UlFtd0h1bFFSVmN4ZnQKRDdlMzJuNG9WenBLRGd0K0hxRDgzYjZuTkgxOUsrbDVaZkk5eVRONlNYYmdHMGhOdlZ3bldseTlLODQvZ0FWTQpscmhPSjdYSCtlSFA5ZDAvLzNtZUJYMXpZdisrdmJPeER4NzIwcVZXUmpublJFSHlIOHVyVzdSUEQrNFRtK1pwCmlpSUNMZkxzRk0rKzBHWU5ncVR0UzlOL2p2SWpwRCtGK2V2Uituc0txRUYrYU4yTjYwVXNQN054VjFQYkpzQWYKTlVWZ042U210dVM5VE8vR3BKV0o2QjRTQlZVZDVvY1RET3J6a0JoVW52YU9ySXpsUkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdThFWm02RTNzVnR6ZWRUalNuMS9oRHM0UzNCaDdTRUxhSDRFR3VNcklaSElaK21nCk1TMmVyN0dDNnVEMlpjcGIycFNUaEJWZTBaOGNrcHBtRzBuZ3ErZlpzaTY5aFR0Q3BpNTlYU1poQXVDSmM4RmwKM1VKTWtqaERtdGplaUVXUVhmbEVlRTgzYmNPYjBkd09kRzlLc0UrZ1BZZXlIYmdjbi92OVF5NjNTdEo2RGVhbgpPSXd1N1hBZ1JENjZ1V2lZT2tsUHlrZ0JXMXNhRy9GVmVISW9ZWk8vTU1uTGhMOU1FOWp3dmtHVVc2STVyNlgzCnRIUWRONVlwbW80RTZLakR3L2ZNOXc5ZXVNNHZVNVZGV3BvSFM0RUhWcWthamNtWWxFT1lPbDNwWEo5RU5qTU0KS2xqUlFBTEl1NENJZzRnN3k2UVFwM1pyaStvYkU2Wmc4ekxobVFJREFRQUJBb0lCQVFDcmJMSngyeS9iV2xGRAowbkU0S1ArTmZ2aDJRSVRZbWt3dE9xbUsxeEVoVkZhek1hY1dYNzI4VW9uaTVFVjBTTisyNGVNU1BPVFc1YnlUCnlpOGlDVUQrRS9FNjg5d01Va0FYTk9rM2JIdzB3VWdlalZ6eE9NQnEzTDQxR24rTDBsL3V2VkdidTFBemd0NjUKTEg5eUpjNyt6YVRUcVJxaWNlQ0kzZTJ1TW5BZCtoNmM3b0hCTVd4VmFJaEZtOG1ZVUVuby9oazdVSG1GWVltYQpXbzJwSEZIRXVwMUsvNzRZakt3cmZXV2hHejAvbERYUVFjYm9ub2Yzd1oxRFhRT0R1QzFYWmJxWDFpVWdvZURyCjIyZUpXeGl4UlM4NFQ2VGlCRXlwa2dxSHdWMzRtWERadWdNT0R0VmZYYllud1R4VlFTdjhHOUozU2x2dWRPS3IKVnpLZVgrK1ZBb0dCQU1qUEgwSXY0dzk1bUxPQVBobGZoNkU0M3k4anRwREpua0J4Ni9ydE9oZGZEZ2d2VFE5Zgp1ZHJhTEUwLzFnN2ZlaEhDbEhEZGlJZUxHbGhpK05kdVVCQ3hGTmtYckxBUGVkY2ozZVUxS0VvbkFTSkNCYVJXCisrc2dhd2VjRTZtNE01cm5KTU8yNUZVRG1meS8wKzhEaVRldnpNb1FrVks1Rm9mWTdFN3hxaks3QW9HQkFPOWIKY25zRFAzSmxlL0IxbHZmdlJ2SUx1STVoK3RjaUlrMG9NeWd3bG5yeHdpTVY2bm9ZV3E4aXZwMlNEYnN6SHNhNQp3SXZxaWVJVk1UcSsyU1NnbFRjMHp3elJIMjZYT2w1ZGlRKzRRRWIrL1BKNE5CV1FqNmdVWFVicXh4bEx6WFlNCnh2R0hXR05QVDN2MXdYT2RGelJZWTFwZ1JDUjZkNzI0YkcyWThjbTdBb0dCQU1pWS82VGlxWFNBQitib3FTQTMKcWdtSUFvdllwVHVsN1F4N3dUeDlWcGFhUWk0eThrdjFXSGdqa2pYcEd6RG9WYzBBRDhGZnpFOTZ5ZXFaay9QQgpJd0pKbzRYcWZIdTBPZ2FNc2RHU2RKait0Y2MvSk51eWVSMjgySzVWWDk4ZlA0M3ljV3VCZkQ3Z3hpY1NpZWd1CkpCa1k2UDdCNWlvNDh5VHBzY1o2NjRhWkFvR0FQaU9waHRJRENMbmNBVU1sM0Z3Y09QNWQvV2ptYkMrS1pDbUoKam1kK3laQTE3RkhtTzZoUzhxQzhoNy9CSE5aYXFSRFVNZjdEcVJRRFlkTG1JS0luMnRzMDNZajA5Z3NBdGpybQpPRlNISzJkTFY4OXBCaWd2ZzEwMkVoRWxleVc0dzJyeHd3WjJKZUlUS29WVW9hVW92d2dyVXUwbkE2bGZxTHRXCk91VzM3NzBDZ1lBbVduelozL1luT0RReEpvTUY4TFYzZldZNlQ4OGJvRE9QU3p1cGlRNlFEM1pNa1JraGFCTU8KZVpYS1YzL3F6aUxqWmZiZjhrclhRZzl3Ky9sUTBxMERrS2lpWkIybUVMNEpIbCtJWmRVVWtrb3BhRk0xdWtkUApFcVU4YWluMkJwdUZMdGxmMVJiSE11WFFJQk5NQVZDemRETnVGR0ttbEwvL1pHS0h5RFFzMUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=