apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: test1-unhealthy
spec:
  clusterName: test1
  maxUnhealthy: 100%
  nodeStartupTimeout: 10m
  selector:
    matchLabels:
      cluster.x-k8s.io/deployment-name: test1-md-0
  unhealthyConditions:
    - type: Ready
      status: Unknown
      timeout: 1s
